// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var autocompleteSearchResponse = AutocompleteSearchResponse.FromJson(jsonString);

namespace QuickType
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class AutocompleteSearchResponse
    {
        [JsonProperty("Version")]
        public long Version { get; set; }

        [JsonProperty("Key")]
        [JsonConverter(typeof(ParseStringIntConverter))]
        public int Key { get; set; }

        [JsonProperty("Type")]
        public string Type { get; set; }

        [JsonProperty("Rank")]
        public long Rank { get; set; }

        [JsonProperty("LocalizedName")]
        public string LocalizedName { get; set; }

        [JsonProperty("Country")]
        public AdministrativeArea Country { get; set; }

        [JsonProperty("AdministrativeArea")]
        public AdministrativeArea AdministrativeArea { get; set; }
    }

    public partial class AdministrativeArea
    {
        [JsonProperty("ID")]
        public string Id { get; set; }

        [JsonProperty("LocalizedName")]
        public string LocalizedName { get; set; }
    }

    public partial class AutocompleteSearchResponse
    {
        public static List<AutocompleteSearchResponse> FromJson(string json) => JsonConvert.DeserializeObject<List<AutocompleteSearchResponse>>(json, QuickType.Converter.Settings);
    }

}
